### ISSUE TITLE
Problem when I compiling from source

### ISSUE THREAD

**Issue by rpayanm** [alphaonex86/Ultracopier#10]
[For compile from source](http://ultracopier-wiki.first-world.info/wiki/Compilation_of_Ultracopier) I do this:

``````
$ git clone https://github.com/alphaonex86/Ultracopier.git
$ cd Ultracopier
$ qmake;make
Usage: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake [mode] [options] [files]

QMake has two modes, one mode for generating project files based on
some heuristics, and the other for generating makefiles. Normally you
shouldn't need to specify a mode, as makefile generation is the default
mode for qmake, but you may use this to test qmake on an existing project

Mode:
  -project       Put qmake into project file generation mode
                 In this mode qmake interprets files as files to
                 be built,
                 defaults to *; *; *; *.ts; *.xlf; *.qrc
                 Note: The created .pro file probably will 
                 need to be edited. For example add the QT variable to 
                 specify what modules are required.
  -makefile      Put qmake into makefile generation mode (default)
                 In this mode qmake interprets files as project files to
                 be processed, if skipped qmake will try to find a project
                 file in your current working directory

Warnings Options:
  -Wnone         Turn off all warnings; specific ones may be re-enabled by
                 later -W options
  -Wall          Turn on all warnings
  -Wparser       Turn on parser warnings
  -Wlogic        Turn on logic warnings (on by default)
  -Wdeprecated   Turn on deprecation warnings (on by default)

Options:
   * You can place any variable assignment in options and it will be     *
   * processed as if it was in [files]. These assignments will be parsed *
   * before [files].                                                     *
  -o file        Write output to file
  -d             Increase debug level
  -t templ       Overrides TEMPLATE as templ
  -tp prefix     Overrides TEMPLATE so that prefix is prefixed into the value
  -help          This help
  -v             Version information
  -after         All variable assignments after this will be
                 parsed after [files]
  -norecursive   Don't do a recursive search
  -recursive     Do a recursive search
  -set <prop> <value> Set persistent property
  -unset <prop>  Unset persistent property
  -query <prop>  Query persistent property. Show all if <prop> is empty.
  -cache file    Use file as cache           [makefile mode only]
  -spec spec     Use spec as QMAKESPEC       [makefile mode only]
  -nocache       Don't use a cache file      [makefile mode only]
  -nodepend      Don't generate dependencies [makefile mode only]
  -nomoc         Don't generate moc targets  [makefile mode only]
  -nopwd         Don't look for files in pwd [project mode only]
make: *** No targets specified and no makefile found.  Stop. ```

What I am doing wrong?
``````

**Comment by alphaonex86** [comment]
You need specify the .pro file like this:
qmake ultracopier-core.pro
And after:
make

**Comment by rpayanm** [comment]
@alphaonex86 Thank you for your answer, but now I have this error:
```
$ qmake ultracopier-core.pro
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
```

Greetings.

**Comment by alphaonex86** [comment]
You should generate the .qm, take look to this:
https://github.com/alphaonex86/Ultracopier/tree/master/tools/to-pack
My compilation chain

**Comment by Neutrynos** [comment]
Hi,
I've got the same issue as rpayanm :

$ qmake ultracopier-core.pro
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'

I looked at tools/to-pack/ directory but did'nt found anything to generate the .qm, how should I do ?

**Comment by alphaonex86** [comment]
https://github.com/alphaonex86/Ultracopier/blob/master/tools/to-pack/sub-script/translation.sh#L16

It do: lrelease -nounfinished -compress -removeidentical XXXXX.pro dans generate the .qm file

**Comment by Neutrynos** [comment]
Thanks it works. It was on the wiki but I thought it was to do after qmake.
But now I've got a new issue when doing "make" command. 

DebugEngine.h:19:30: fatal error: QRegularExpression: No such file or directory

I tried to google it but i did'nt found anything yet.

**Comment by rpayanm** [comment]
@alphaonex86 Why do not compile the project (.deb, .rpm, etc.) for new users as we do not spend so much work.

**Comment by alphaonex86** [comment]
@Neutrynos : QRegularExpression: No such file or directory -> Are you well using Qt5?

@rpayanm : Because it's lot of work to do for all distro, and have some compatibility problem. And I failed to use: http://openbuildservice.org/about/ then I prefer help the distro with this.

**Comment by Neutrynos** [comment]
I understand it's a lot of work. To help a little I can make a tutorial for my version of Debian when all my problems will be gone.

@alphaonex86 : I made some changes and now I'm running with qt5 (I replace qt4-default by qt5-default in synaptic) 
Ultracopier-master# qmake --version
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/x86_64-linux-gnu

But still have issues : ui_HelpDialog.h:13:25: fatal error: QtGui/QAction: No such file or directory

**Comment by Neutrynos** [comment]
I post too quickly, after doing make clean and then make it works

**Comment by alphaonex86** [comment]
@Neutrynos: yes please, a tutorial can be useful, I will post on the wiki.

Keep sure the build is clear: seam the ui_HelpDialog.h is generated with Qt4, but try compil with Qt5: make clear

... your next comment confirm it ;)

**Comment by vishalpb** [comment]
@alphaonex86 : I am stuck at compilation. I am using kubuntu 16.04, with qt4-dev-tools installed and system is updated till date, downloaded the latest download (ver 1.2.3.5) at http://ultracopier.first-world.info/. Have tried to compile for "ultracopier-core.pro" as well as "ultracopier-all-in-one-direct.pro"

vpb@VPB-Kubuntu:~/Downloads/ultracopier-src$ qmake ultracopier-core.pro;make                                                     
g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Ilib/qt-tar-xz -I. -I. -o ThemesManager.o ThemesManager.cpp                                                                                                     
In file included from DebugEngineMacro.h:15:0,
                 from Environment.h:11,
                 from ThemesManager.h:17,
                 from ThemesManager.cpp:12:
DebugEngine.h:19:30: fatal error: QRegularExpression: No such file or directory
compilation terminated.                                                                                                                                      
Makefile:796: recipe for target 'ThemesManager.o' failed                                                                                                     
make: *** [ThemesManager.o] Error 1        


**Please provide a way out.**

Thanks

**Comment by alphaonex86** [comment]
Hello,

Ultracopier is Qt5, not Qt4.

I have fix some topic, where do you have see this?


Cheers,


On 10/08/16 23:08, vishalpb wrote:
> @alphaonex86 : I am stuck at compilation. I am using kubuntu 16.04, with qt4-dev-tools installed and system is updated till date, downloaded the latest download (ver 1.2.3.5) at http://ultracopier.first-world.info/. Have tried to compile for "ultracopier-core.pro" as well as "ultracopier-all-in-one-direct.pro"
>
> vpb@VPB-Kubuntu:~/Downloads/ultracopier-src$ qmake ultracopier-core.pro;make                                                     
> g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Ilib/qt-tar-xz -I. -I. -o ThemesManager.o ThemesManager.cpp                                                                                                     
> In file included from DebugEngineMacro.h:15:0,
>                  from Environment.h:11,
>                  from ThemesManager.h:17,
>                  from ThemesManager.cpp:12:
> DebugEngine.h:19:30: fatal error: QRegularExpression: No such file or directory
> compilation terminated.                                                                                                                                      
> Makefile:796: recipe for target 'ThemesManager.o' failed                                                                                                     
> make: *** [ThemesManager.o] Error 1        
>
>
> **Please provide a way out.**
>
> Thanks
>

-- 
alpha_one_x86/BRULE Herman <alpha_one_x86@first-world.info>
Main developer of Supercopier/Ultracopier/CatchChallenger, Esourcing and server management
IT, OS, technologies, research & development, security and business department

**Comment by vishalpb** [comment]
I followed the instruction on the wiki page : http://ultracopier-wiki.first-world.info/wiki/Compilation_of_Ultracopier . It is mentioned here as:
"Install the tool to compil if needed
ubuntu
sudo apt-get install qt4-dev-tools build-essential dev-tools qt4-dev qt4-qmake "

Also while compiling earlier I had come across an error where both 'resources/ultracopier-resources.qrc' and 'plugins/static-plugins.qrc' gave an error for fetching the translation.qm file from their respective language folders respectively looking for 'translation.qm' in /resources/languages/en/ and /plugins/languages/fr/. Had to modify the ultracopier-resources.qrc and static-plugins.qrc to fetch the 'translation.ts' instead of 'translation.qm'


Now stuck at [ThemesManager.o] error. Will install Qt5 and try.

**Comment by alphaonex86** [comment]
Ok, I have fixed this page with:
sudo apt-get install build-essential gcc automake qt5-qmake liblzma-dev qttools5-dev qt5-default

Don't change .qm to .ts, it's not the same format.
find ./ -name '*.ts' -exec lrelease {} \; should generated the .qm missing

**Comment by vishalpb** [comment]
Thanks for instructions on qt5 installation and .qm, both worked but still getting error while making ultracopier


**Error Log:**
---------------------------------------------------------------
vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ sudo apt-get install build-essential gcc automake qt5-qmake liblzma-dev qttools5-dev qt5-default
Reading package lists... Done
Building dependency tree       
Reading state information... Done
automake is already the newest version (1:1.15-4ubuntu1).
build-essential is already the newest version (12.1ubuntu2).
gcc is already the newest version (4:5.3.1-1ubuntu1).
liblzma-dev is already the newest version (5.1.1alpha+20120614-2ubuntu2).
qttools5-dev is already the newest version (5.5.1-3build1).
qt5-qmake is already the newest version (5.5.1+dfsg-16ubuntu7.1).
qt5-default is already the newest version (5.5.1+dfsg-16ubuntu7.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ qmake ultracopier-all-in-one-direct.pro;make
g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE_DIRECT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ThemesManager.o ThemesManager.cpp
In file included from plugins/Themes/Oxygen/ThemesFactory.h:19:0,
                 from ThemesManager.cpp:20:
./ui_themesOptions.h:13:25: fatal error: QtGui/QAction: No such file or directory
compilation terminated.
Makefile:1535: recipe for target 'ThemesManager.o' failed
make: *** [ThemesManager.o] Error 1

vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ qmake ultracopier-core.pro;make
g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ThemesManager.o ThemesManager.cpp
g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ResourcesManager.o ResourcesManager.cpp
g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
In file included from HelpDialog.h:15:0,
                 from EventDispatcher.h:20,
                 from main.cpp:10:
ui_HelpDialog.h:13:25: fatal error: QtGui/QAction: No such file or directory
compilation terminated.
Makefile:1094: recipe for target 'main.o' failed
make: *** [main.o] Error 1
vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ 

------------------------------------------------

As for the "QtGui/QAction: No such file or directory error", I got this when googled:

In Qt5, QAction header is in QtWidgets include sub-directory, not in QtGui (that's true for Qt4). Though you don't actually need to specify include sub-directories since qmake will handle that for you. You just need to add QT += widgets to your .pro file.

Tried setting 'QT +=widgets' in Ultracopier-all-in-one-direct.pro but it did not work. Could not find any other files to include the above command. 
Pls help

P.S: As I am not well acquainted with linux, not able to resolve the problems.

**Comment by vishalpb** [comment]
Thanks @alphaonex86  for the qt5 apt-get command and clarification on .qm
Sorry I missed the .qm compilation command though it was there on instructions page.

Installed Qt5, created .qm. Further as suggested by Neutrynos I did the make clean and compile the all-in-one-direct binary.


On the instructions wiki page (http://ultracopier-wiki.first-world.info/wiki/Compilation_of_Ultracopier), after the compilation of binary you have mentioned about plugin and using the same compilation commands for plugin. Can you please provide example or actual commands for the same.

Also, can you shed more light on how to execute the 'assemble this structure into search path': Do we just need to edit some file or execute a command???

Apologies for such trivial questions but as am a beginner in linux and sometimes can find the required solution after googling, thus such questions. Please bear with me.

**Comment by alphaonex86** [comment]
Hello, do a:

make distclean

To clean old Qt4 file and try form qmake command again, be sure it's
qmake of qt5 by: qmake -v


On 10/12/16 19:32, vishalpb wrote:
> Thanks for instructions on qt5 installation and .qm, both worked but still getting error while making ultracopier
>
>
> **Error Log:**
> ---------------------------------------------------------------
> vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ sudo apt-get install build-essential gcc automake qt5-qmake liblzma-dev qttools5-dev qt5-default
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> automake is already the newest version (1:1.15-4ubuntu1).
> build-essential is already the newest version (12.1ubuntu2).
> gcc is already the newest version (4:5.3.1-1ubuntu1).
> liblzma-dev is already the newest version (5.1.1alpha+20120614-2ubuntu2).
> qttools5-dev is already the newest version (5.5.1-3build1).
> qt5-qmake is already the newest version (5.5.1+dfsg-16ubuntu7.1).
> qt5-default is already the newest version (5.5.1+dfsg-16ubuntu7.1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>
> vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ qmake ultracopier-all-in-one-direct.pro;make
> g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE_DIRECT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ThemesManager.o ThemesManager.cpp
> In file included from plugins/Themes/Oxygen/ThemesFactory.h:19:0,
>                  from ThemesManager.cpp:20:
> ./ui_themesOptions.h:13:25: fatal error: QtGui/QAction: No such file or directory
> compilation terminated.
> Makefile:1535: recipe for target 'ThemesManager.o' failed
> make: *** [ThemesManager.o] Error 1
>
> vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ qmake ultracopier-core.pro;make
> g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ThemesManager.o ThemesManager.cpp
> g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ResourcesManager.o ResourcesManager.cpp
> g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -Ilib/qt-tar-xz -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
> In file included from HelpDialog.h:15:0,
>                  from EventDispatcher.h:20,
>                  from main.cpp:10:
> ui_HelpDialog.h:13:25: fatal error: QtGui/QAction: No such file or directory
> compilation terminated.
> Makefile:1094: recipe for target 'main.o' failed
> make: *** [main.o] Error 1
> vpb@VPB-Kubuntu:~/Downloads/NewFolder/ultracopier-src$ 
>
> ------------------------------------------------
>
> As for the "QtGui/QAction: No such file or directory error", I got this when googled:
>
> In Qt5, QAction header is in QtWidgets include sub-directory, not in QtGui (that's true for Qt4). Though you don't actually need to specify include sub-directories since qmake will handle that for you. You just need to add QT += widgets to your .pro file.
>
> Tried setting 'QT +=widgets' in Ultracopier-all-in-one-direct.pro but it did not work. Could not find any other files to include the above command. 
> Pls help
>
> P.S: As I am not well acquainted with linux, not able to resolve the problems. 
>

-- 
alpha_one_x86/BRULE Herman <alpha_one_x86@first-world.info>
Main developer of Supercopier/Ultracopier/CatchChallenger, Esourcing and server management
IT, OS, technologies, research & development, security and business department

**Comment by alphaonex86** [comment]
Forget ths plugin for ultracopier-all-in-one-direct.pro

**Comment by vishalpb** [comment]
As suggested in assemble section, edited (replaced to <architecture>linux-x86_32-pc</architecture>) the informations.xml in the following:
CopyEngine/Ultracopier/informations.xml
Themes/Oxygen/informations.xml
Listener/catchcopy-v0002/informations.xml
SessionLoader/KDE4/informations.xml

Did not understand "Assemble this structure into search path (~/.config/Ultracopier/, near the binary, /usr/share/ultracopier/, /usr/lib/ultracopier/), given for linux (remplace .so by .dll or .dylib if needed)"

Uninstalled qt4, installed qt5 (qmake -v gives: QMake version 3.0; Using Qt version 5.5.1 in /usr/lib/i386-linux-gnu)
Did the make distclean, then did 'qmake ultracopier-all-in-one-direct.pro;make' 
Am I missing anything now? 

Tried 'make install' after 'qmake ultracopier-all-in-one-direct.pro;make' , but make install doesn't work.

**Comment by alphaonex86** [comment]
No, just that's work.  "Assemble this structure into search path" is for plugins. Not needed in your case.

make install not work, just start the binary.

**Comment by vishalpb** [comment]
Thanks. Started the binary. 
I am being asked for a key (I thought ultracopier is free as the same is mentioned on the website) . 
Further another error "The replacement of default copy/move is not supported by the File Manager (Dolphin, Nautilus, ...)

![screenshot_20161013_200212](https://cloud.githubusercontent.com/assets/22717379/19353147/0661c5c4-9180-11e6-85f9-61ade671bdd0.png)

**Comment by alphaonex86** [comment]
Into Variable.h, comment the line #define ULTRACOPIER_VERSION_ULTIMATE

Yes, you need ask more intergration on KDE about this part.
