### ISSUE TITLE
 UAC related problem 

### ISSUE THREAD

**Issue by Letsdiehottie** [alphaonex86/Ultracopier#107]
1. Ultracopier can't work unless user account control is on
2. Add feature  that (hide tray icon )like supercopier2.2 beta 
3. Sorry to say that but the supercopier 2.2 beta works perfectly more than ultracopier with size 100 and something kb
4. But it miss auto shutdown after finish with selective minutes give it a try and fix your copier 

Ultracopier is 20MB

Please Do Set copier engine to use  windows buffer size by default 

I mean no offending
Thank you for reading 
Delete my massage if  wish ..i only want to give you good feedback for your ultracopier next update to be perfect like it was in the past... supercopier 2.2beta

**Comment by alphaonex86** [comment]
1. In case of UAC detect, it request it, in default behavior this open user dialog to ask
2. Windows do it, since Windows XP with auto-hide if I totally remove it, this will treat ultracopier as malware for this behavior because it will considere it try hide it self
3. Can you re-sentence this part?
4. Can you re-sentence the end? Because Ultracopier have already shutdown at end

Yes Ultracopier is 20MB, 1MB for Ultracopier, rest for Qt, Qt is UI graphical toolkit to do the interface.

**Comment by Letsdiehottie** [comment]
3.have you used supercopier 2.2 beta ? https://github.com/gligli/SuperCopier2/releases/download/2.2b/SuperCopier22beta.exe

-in supercopier 2.2beta options there is an option that says (hide tray icon)i think it makes it work like service in background..and windows treat it normally not a 
malware .. 
I'll give you screen shots in next hour 
-the skin is the same in ultracopier and supercopier 

4.ultra copier has shutdown at the end but immediately and thats is bad to the external hard drive ..make it at least 2 minutes count down before shutdown and make option for cancelling shutdown

-supercopier 2.2beta does not has auto shutdown 

5. Ultracopier is an updated version of supercopier but with some deleted features ? Or they have different developers ?

**Comment by alphaonex86** [comment]
3. Yes during years, and I have maintained this version too, the times have change, and now all is not clear is consider as malware, not by windows, by users, and if I have massive report then I will be blocked. For the user this features will be considered as a try to hide Ultracopier and prevent be able to quit. And again exists a function into Windows to do it
4. auto shutdown is an option, not mandatory. I will add into my todo to add time and able to cancel
5. Different developer than 2.2 version, but I'm the dev of Supercopier and Ultracopier. Some features is delete for some reason, lot of stuff have changed, new stuff exists, but the more important: A good focus will be around the data, since 2.2b lot of code have been improved in this way
6. Sorry but I can't disable security of Windows, you have to ask it to Microsoft, pass by UAC is the unique way to inject .dll into explorer.exe into modern Windows. No way to pass copy/move to Ultracopier without this.

**Comment by Letsdiehottie** [comment]
6. See for your self install supercopier 2.2beta ..it works fine and perfectly on windows 11 23h2 and 24h2 and windows 10 22h2 without UAC on ..i tested it myself..also teracopy works no UAC needed
7. I hope you will find a way around it 
8. The reason why i ask to make ultracopier works without UAC on ..is windows is much faster no need to elevate any app  all apps works as admin
9.i tried run as administrator in ultracopier.exe properties compatibility option and didn't listen on explorer.exe 
Just check 2.2beta and see how it doesn't need uac 

And again sorry to bother you 💙

**Comment by alphaonex86** [comment]
6. The code is open source, anyone can contribute. For now I failed to improve this part, I hope some windows dev can help on this part.

**Comment by Letsdiehottie** [comment]
Or you can delete the (beta word from about section )on the open source supercopier 2.2 beta and add the shutdown timer with optional cancel  and That's it u have the perfect copy app tested by many users 😁https://github.com/gligli/SuperCopier2/releases/download/2.2b/SuperCopier22beta.exe

**Comment by alphaonex86** [comment]
No, because is not maintained and a data can be lost. I will not be responsive of that's.
