### ISSUE TITLE
In some case, drag'n'drop from 7zip archive in explorer++ doesn't work.

### ISSUE THREAD

**Issue by pseudo555** [alphaonex86/Ultracopier#60]
Issue might be on explorer++ side, but no guarantee.
Issue was reported in explorer++ there : https://github.com/derceg/explorerplusplus/issues/336

In short:

Explorer++ beta version.
Windows 11 (10 21h1 / 21h2 also reproduced the issue)
7zip 19.00
Ultracopier 2.2.4.14 (have it replace windows feature)

Get an archive file (zip / 7z or rar).
Open it with your archiver software (in my case 7zip 19.00)
open explorer++ in any folder where you are granted write permission (ie %temp% on windows) 
Drag files/folder from the arhive open to the explorer folder.

Observed: 7zip says it can write file ("wrong modification date or unable to get it. try to disable the transfert of that one" from french to bad english by myself)
Expected : it works.

Killing ultracopier (so leting windows handle the copy/move/paste) resolve the issue.

**Comment by alphaonex86** [comment]
Hi,
This is more linked with https://github.com/alphaonex86/Catchcopy
Windows API only send move/copy without return, mean:

- 7zip create temporary archive
- explorer.exe send the copy to do to Ultracopier (via plugin Catchcopy)
- explorer.exe return copy done
- 7zip delete temporary file
- Ultracopier start copy
- Ultracopier failed because the source archive not exists

**Comment by pseudo555** [comment]
Possible, i'm not expert on how ultracopier works.
So should i create an issue there and close this one ?

**Comment by alphaonex86** [comment]
correct
